# Generated by Django 4.0.2 on 2022-02-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_1', models.IntegerField()),
                ('mobile_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=60)),
                ('tech', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=10)),
                ('rollNo', models.IntegerField(db_column='rollNo')),
                ('name', models.CharField(max_length=60)),
                ('fatherName', models.CharField(max_length=60)),
                ('className', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_1', models.IntegerField()),
                ('mobile_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAllotmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=2)),
                ('rollNo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_student', to='collegeAdmin.student')),
                ('rollNo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_student', to='collegeAdmin.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_session', to='collegeAdmin.student')),
            ],
        ),
    ]
