# Generated by Django 4.0.2 on 2022-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffMember',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('userName', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ProjectAllotmentTable',
        ),
    ]
