# Generated by Django 4.0.2 on 2022-02-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_1', models.IntegerField()),
                ('mobile_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=60)),
                ('tech', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='staffMember',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('userName', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('session', models.CharField(max_length=10)),
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('fatherName', models.CharField(max_length=60)),
                ('className', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_1', models.IntegerField()),
                ('mobile_2', models.IntegerField()),
            ],
        ),
    ]
