# Generated by Django 4.0.2 on 2022-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='mobile_2',
            field=models.IntegerField(blank=True),
        ),
    ]
