# Generated by Django 4.0.2 on 2022-03-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmin', '0002_staffmember_remove_student_id_alter_student_rollno_and_more'),
        ('staff', '0004_alter_guide_mobile_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=4)),
                ('guide', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='collegeAdmin.guide')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='collegeAdmin.project')),
                ('student_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_student', to='collegeAdmin.student')),
                ('student_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='second_student', to='collegeAdmin.student')),
            ],
        ),
        migrations.DeleteModel(
            name='guide',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='staffMember',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
