# Generated by Django 4.0.2 on 2022-03-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmin', '0002_staffmember_remove_student_id_alter_student_rollno_and_more'),
        ('staff', '0005_allocationtable_delete_guide_delete_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationtable',
            name='group',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='allocationtable',
            name='guide',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='collegeAdmin.guide'),
        ),
    ]
